name: Run Postman Tests (Newman)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: ğŸ“¦ Instalar o Newman
        run: npm install -g newman

      - name: â–¶ï¸ Rodar a Collection
        run: |
          newman run ServeRest-Collection.postman_collection.json \
            -e ServeRest-Environment.postman_environment.json \
            --reporters cli,html \
            --reporter-html-export newman-report.html

      - name: ğŸ“„ Upload do relatÃ³rio HTML gerado
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.html
