name: Run Postman Tests (Newman)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar o Newman e Reporter htmlextra
        run: |
          npm config set prefix /usr/local
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Rodar a Collection
        run: |
          ls -la # para listar arquivos e verificar se existe
          newman run "Testes ServeRest.postman_collection.json" -e "Variaveis ServeRest.postman_environment.json" -r cli,htmlextra --reporter-htmlextra-displayProgressBar --reporter-htmlextra-title "Relatório do CEO Johnny Melo" --reporter-htmlextra-export newman-report.html

      - name: Upload do relatório HTML gerado
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
